# https://docs.netlify.com/configure-builds/file-based-configuration/
  
[build]
  functions = "functions"
    
[[redirects]]
  from = "/*"
  to = "/dashboard"
  status = 200
  force = false
  query = {path = ":path"} 
  conditions = {Role = ["admin", "user"]}

[[redirects]]
  from = "/get-authors"
  to = "/.netlify/functions/get-authors"
  status = 200

[[redirects]]
  from = "/get-courses"
  to = "/.netlify/functions/get-courses"
  status = 200
  
[[redirects]]
  from = "/create-course"
  to = "/.netlify/functions/create-course"
  status = 200
  
[[redirects]]
  from = "/update-course/*"
  to = "/.netlify/functions/update-course/:splat"
  status = 200
  
[[redirects]]
  from = "/update-course"
  to = "/.netlify/functions/update-course"
  status = 200
  
[[redirects]]
  from = "/delete-course/"
  to = "/.netlify/functions/delete-course"
  status = 200

[[redirects]]
  from = "/delete-inventory-item/*"
  to = "/.netlify/functions/delete-inventory-item/:splat"
  status = 200

[[redirects]]
  from = "/get-dashboard-data"
  to = "/.netlify/functions/get-dashboard-data"
  status = 200

[[redirects]]
  from = "/get-inventory-items"
  to = "/.netlify/functions/get-inventory-items"
  status = 200

[[redirects]]
  from = "/get-user-bio"
  to = "/.netlify/functions/get-user-bio"
  status = 200

[[redirects]]
  from = "/get-users"
  to = "/.netlify/functions/get-users"
  status = 200

[[redirects]]
  from = "/update-user-bio"
  to = "/.netlify/functions/update-user-bio"
  status = 200

[[redirects]]
  from = "/create-inventory-item"
  to = "/.netlify/functions/create-inventory-item"
  status = 200
