# https://docs.netlify.com/configure-builds/file-based-configuration/
  
[build]
  functions = "functions"

[[redirects]]
    from = "/api/*"
    to= "/.netlify/functions/:splat"
    status = 200

[[redirects]]
  from = "/delete-inventory-item/*"
  to = "/.netlify/functions/delete-inventory-item/:splat"
  status = 200
